# Generated by Django 3.0.7 on 2020-06-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200617_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
