# Generated by Django 3.0.7 on 2020-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200617_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
